name: players_bank_redesign
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_state_city_picker: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Greycliff
      fonts:
        - asset: assets/fonts/Greycliff_Bold.otf
          weight: 700
        - asset: assets/fonts/Greycliff_Regular.otf
          weight: 400
    - family: Barracuda
      fonts:
        - asset: assets/fonts/Barracuda_Bold.ttf
          weight: 700
        - asset: assets/fonts/Barracuda_Light.ttf
          weight: 300
        - asset: assets/fonts/Barracuda_Regular.ttf
          weight: 400
